name: video_call_app
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  agora_rtc_engine: ^6.5.3
  flutter_riverpod: ^3.0.3
  fluttertoast: ^9.0.0
  intl: ^0.20.2
  google_fonts: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
